export const sections_CCS = [
  // InfoTech
  { value: "INFO1A" },
  { value: "INFO1B" },
  { value: "INFO1C" },
  { value: "INFO1D" },
  { value: "INFO1E" },
  { value: "INFO1F" },
  { value: "INFO2A" },
  { value: "INFO2B" },
  { value: "INFO2C" },
  { value: "INFO2D" },
  { value: "3WMAD1" },
  { value: "3WMAD2" },
  { value: "3NA1" },
  { value: "3NA2" },
  { value: "3SMP1" },
  { value: "4WMAD1" },
  { value: "4WMAD2" },
  { value: "4SMP1" },
  { value: "4SMP2" },
  // CS
  { value: "CS1A" },
  { value: "CS1B" },
  { value: "CS2A" },
  { value: "CS2B" },
  { value: "3IS1" },
  { value: "3IS2" },
  { value: "4IS1" },
  { value: "4IS2" },
];

export const sections_CAS = [
  { value: "1B1" },
  { value: "1B2" },
  { value: "2B1" },
  { value: "2B2" },
  { value: "3B1" },
  { value: "3B2" },
  { value: "4B1" },
  { value: "4B2" },
  { value: "1P1" },
  { value: "1P2" },
  { value: "1P3" },
  { value: "1P4" },
  { value: "2P1" },
  { value: "2P2" },
  { value: "2P3" },
  { value: "2P4" },
  { value: "3P1" },
  { value: "3P2" },
  { value: "3P3" },
  { value: "3P4" },
  { value: "4P1" },
  { value: "4P2" },
  { value: "4P3" },
  { value: "4P4" },
];

export const sections_SHS = [
  { value: "ABM-1A" },
  { value: "ABM-1B" },
  { value: "ABM-2A" },
  { value: "ABM-2B" },
  { value: "HUMSS-1A" },
  { value: "HUMSS-1B" },
  { value: "HUMSS-1C" },
  { value: "HUMSS-2A" },
  { value: "HUMSS-2B" },
  { value: "STEM-1A" },
  { value: "STEM-1B" },
  { value: "STEM-1C" },
  { value: "STEM-1D" },
  { value: "STEM-2A" },
  { value: "STEM-2B" },
  { value: "STEM-2C" },
  { value: "STEM-2D" },
  { value: "TVL-1A" },
  { value: "TVL-1B" },
  { value: "TVL-2A" },
  { value: "TVL-2B" },
];
