import Navbar from "@/components/Navbar";
import { Inter, Margarine } from "next/font/google";

import "./globals.css";
import { NextAuthProvider } from "./providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });
const margarine = Margarine({ weight: "400", preload: false });

const inter_init = inter.className;

export const metadata = {
  title: "SmartScore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter_init} ${margarine}`}>
        <NextAuthProvider>
          <div className="md:hidden">
            <Navbar />
          </div>
          <div className="flex flex-col max-md:pt-24">{children}</div>
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
