
import Navbar from '@/components/Navbar';
import { Inter } from 'next/font/google';

import './globals.css';
import { NextAuthProvider } from './providers';
import { Toaster } from '@/components/ui/toaster';



const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'SmartScore',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">


      <body className={inter.className}>

        <NextAuthProvider>
          <div className='flex flex-col'>
            <Navbar />
            {children}
          </div>
          <Toaster />
        </NextAuthProvider>

      </body>


    </html>
  )
}
