
import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { NextAuthProvider } from './providers';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';



const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'SmartScore',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">


      <body className={inter.className}>

        <NextAuthProvider>
          <div className='flex flex-col'>
            <Navbar />
            {children}
          </div>

        </NextAuthProvider>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored" />
      </body>


    </html>
  )
}
